
POST http://localhost:8089/v1/api-docs/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "email":  "no@esprit.tn",
  "motDePasse": "00000000"
}
> {% client.global.set("auth-token", response.body.access_token);  %}



###
POST http://localhost:8089/v1/api-docs/auth/Register
Content-Type: application/json
Accept: application/json

{
  "nom": "string",
  "prenom": "string",
  "email": "no@esprit.tn",
  "phoneNumber": "+88 07537160 8",
  "motDePasse": "00000000",
  "roles": "Student"
}












### Change the password
PATCH http://localhost:8089/v1/api-docs/api/users
Content-Type: application/json
Authorization: Bearer  {{auth-token}}
Accept: application/json


{
  "currentPassword": "00000000",
  "newPassword": "newPassword",
  "confirmationPassword":  "newPassword"
}

### Login again and update the token

POST  http://localhost:8089/v1/api-docs/auth/authenticate
Content-Type: application/json
Accept: application/json


{
  "email":  "YT@esprit.tn",
  "motDePasse": "newPassword"
}

> {% client.global.set("new-auth-token", response.body.access_token);  %}

